runtime: python312
service: cip-client

handlers:
  # Serve static assets
  - url: /static
    static_dir: dist/static
    secure: always

  # Serve other static files (favicon, manifest, etc.)
  - url: /(.*\.(json|ico|png|jpg|jpeg|svg|webp|css|js|txt|map))
    static_files: dist/\1
    upload: dist/.*\.(json|ico|png|jpg|jpeg|svg|webp|css|js|txt|map)
    secure: always

  # SPA fallback (React Router support)
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 1
  # target_cpu_utilization: 0.6
  # max_concurrent_requests: 50

service_account: contract-intelligence-platform@appspot.gserviceaccount.com
