runtime: python312

entrypoint: python -m main

instance_class: F2

automatic_scaling:
  min_instances: 0
  max_instances: 1
  # target_cpu_utilization: 0.6
  # max_concurrent_requests: 50

env_variables:
  ENV: "prod"


service_account: contract-intelligence-platform@appspot.gserviceaccount.com
